// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Subasta.Api.Data;

#nullable disable

namespace Subasta.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261003015044_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Subasta.Api.Domain.Auction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Identificador de la subasta");

                    b.Property<int>("BidCount")
                        .HasColumnType("integer")
                        .HasComment("Cantidad de pujas recibidas");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasComment("Categoría del artículo");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Fecha de cierre/adjudicación (UTC)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Fecha de publicación (UTC)");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Precio actual (mejor puja)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasComment("Descripción del artículo");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Fecha/hora de cierre (UTC)");

                    b.Property<decimal>("MinIncrement")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Incremento mínimo entre pujas");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasComment("Usuario que publica la subasta");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Fecha/hora de inicio (UTC)");

                    b.Property<decimal>("StartingPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Precio inicial");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("Estado: Scheduled, Active, Finished, Cancelled");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasComment("Título del artículo");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasComment("Control de concurrencia optimista");

                    b.Property<Guid?>("WinnerId")
                        .HasColumnType("uuid")
                        .HasComment("Usuario adjudicatario");

                    b.Property<Guid?>("WinningBidId")
                        .HasColumnType("uuid")
                        .HasComment("Puja ganadora");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SellerId");

                    b.HasIndex("StartAt");

                    b.HasIndex("WinnerId");

                    b.HasIndex("Status", "EndAt");

                    b.ToTable("auctions", null, t =>
                        {
                            t.HasComment("Artículos publicados para subasta");
                        });
                });

            modelBuilder.Entity("Subasta.Api.Domain.AuctionImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Identificador de la imagen");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid")
                        .HasComment("Subasta a la que pertenece");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Tipo MIME de la imagen");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Fecha de carga (UTC)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasComment("Contenido binario de la imagen");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasComment("Nombre original del archivo");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasComment("Orden de visualización");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.ToTable("auction_images", null, t =>
                        {
                            t.HasComment("Imágenes de los artículos subastados");
                        });
                });

            modelBuilder.Entity("Subasta.Api.Domain.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Identificador de la puja");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasComment("Monto ofertado");

                    b.Property<Guid>("AuctionId")
                        .HasColumnType("uuid")
                        .HasComment("Subasta pujada");

                    b.Property<Guid>("BidderId")
                        .HasColumnType("uuid")
                        .HasComment("Usuario que puja");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Fecha/hora de la puja (UTC)");

                    b.HasKey("Id");

                    b.HasIndex("BidderId");

                    b.HasIndex("AuctionId", "Amount");

                    b.ToTable("bids", null, t =>
                        {
                            t.HasComment("Ofertas (pujas) realizadas");
                        });
                });

            modelBuilder.Entity("Subasta.Api.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasComment("Identificador de la categoría");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasComment("Nombre de la categoría");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("categories", null, t =>
                        {
                            t.HasComment("Categorías de artículos");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Electrónica"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hogar"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Moda"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Vehículos"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Arte y colecciones"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Deportes"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Otros"
                        });
                });

            modelBuilder.Entity("Subasta.Api.Domain.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Identificador de la notificación");

                    b.Property<Guid?>("AuctionId")
                        .HasColumnType("uuid")
                        .HasComment("Subasta relacionada");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Fecha de creación (UTC)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasComment("Indica si fue leída");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Mensaje mostrado al usuario");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasComment("Tipo de notificación");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasComment("Usuario destinatario");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.HasIndex("UserId", "IsRead");

                    b.ToTable("notifications", null, t =>
                        {
                            t.HasComment("Notificaciones enviadas a los usuarios");
                        });
                });

            modelBuilder.Entity("Subasta.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasComment("Identificador único del usuario");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("Fecha de registro (UTC)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasComment("Correo electrónico (único)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasComment("Indica si la cuenta está habilitada");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Hash PBKDF2 de la contraseña");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasComment("Rol: User o Admin");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasComment("Nombre de usuario visible (único)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasComment("Usuarios registrados de la plataforma");
                        });
                });

            modelBuilder.Entity("Subasta.Api.Domain.Auction", b =>
                {
                    b.HasOne("Subasta.Api.Domain.Category", "Category")
                        .WithMany("Auctions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Subasta.Api.Domain.User", "Seller")
                        .WithMany("Auctions")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Subasta.Api.Domain.User", "Winner")
                        .WithMany()
                        .HasForeignKey("WinnerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Category");

                    b.Navigation("Seller");

                    b.Navigation("Winner");
                });

            modelBuilder.Entity("Subasta.Api.Domain.AuctionImage", b =>
                {
                    b.HasOne("Subasta.Api.Domain.Auction", "Auction")
                        .WithMany("Images")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("Subasta.Api.Domain.Bid", b =>
                {
                    b.HasOne("Subasta.Api.Domain.Auction", "Auction")
                        .WithMany("Bids")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Subasta.Api.Domain.User", "Bidder")
                        .WithMany("Bids")
                        .HasForeignKey("BidderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("Bidder");
                });

            modelBuilder.Entity("Subasta.Api.Domain.Notification", b =>
                {
                    b.HasOne("Subasta.Api.Domain.Auction", "Auction")
                        .WithMany()
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Subasta.Api.Domain.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Subasta.Api.Domain.Auction", b =>
                {
                    b.Navigation("Bids");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Subasta.Api.Domain.Category", b =>
                {
                    b.Navigation("Auctions");
                });

            modelBuilder.Entity("Subasta.Api.Domain.User", b =>
                {
                    b.Navigation("Auctions");

                    b.Navigation("Bids");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
